/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_nano_time_NanoTime */

#ifndef _Included_io_nano_time_NanoTime
#define _Included_io_nano_time_NanoTime
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_nano_time_NanoTime
 * Method:    currentTimeMicros
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL
Java_io_nano_time_NanoTime_currentTimeMicros(JNIEnv *, jobject);

/*
 * Class:     io_nano_time_NanoTime
 * Method:    currentTimeNanos
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL
Java_io_nano_time_NanoTime_currentTimeNanos(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
